### ISSUE TITLE
The button does not work not in the master branch

### ISSUE THREAD

**Issue by god1dog** [kouki-dan/action-button#21]
Does this button always work from the master branch? My problem is that the action is different in the branches and I need to run the screen in the current branch

**Comment by kouki-dan** [comment]
Yes. This button works on the default branch of GitHub. Currently, this based on the [`repository_dispatch`](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event) event which dispatches `RepositoryDispatchEvent` to the default branch.

If you want to dispatch events on other than the default branch, you can use the [`Deployment`](https://developer.github.com/v3/repos/deployments/) event. The [`ref`](https://developer.github.com/v3/repos/deployments/#parameters) parameter on the Deployment event can receive any branch.

I'm working to use this Deployment event in this button in #19. But it is work in progress.

**Comment by kouki-dan** [comment]
I added a new feature to dispatch a Deployment event. This screen has a new radio button to select deployment or repository_dispatch. 
<img width="1359" alt="Screen Shot 2020-02-29 at 1 39 13 AM" src="https://user-images.githubusercontent.com/1401711/75567952-c336d900-5a95-11ea-8e77-34fc433c5436.png">

You can choose any branch by using deployment. Here is the screen after clicking the button.
<img width="1359" alt="Screen Shot 2020-02-29 at 1 46 34 AM" src="https://user-images.githubusercontent.com/1401711/75568302-5b34c280-5a96-11ea-9b2f-bc200abd929b.png">

Thank you.
